language: node_js
node_js:
  - "12.18.3"
dist: trusty
sudo: required
branches:
  only:
    - master
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - ./node_modules
before_script:
  - cd web-ui
  - npm install -g @angular/cli
  - npm install
script:
  - npm run test-headless
  - ng build
