language: node_js
node_js:
  - "12.18.3"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - cd web-ui
  - npm install -g @angular/cli
  - npm install --save-dev @angular-devkit/build-angular
  - npm install
script:
  - npm run test-headless
  - ng build
