apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ include "mlaide.fullname" . }}-db-secret
  labels:
    {{- include "mlaide.webserver.labels" . | nindent 4 }}
stringData:
  username: {{ .Values.webserver.mongodb.username }}
  password: {{ .Values.webserver.mongodb.password }}