apiVersion: v1
kind: Secret
type: kubernetes.io/opaque
metadata:
  name: {{ include "mlaide.fullname" . }}-s3-secret
  labels:
    {{- include "mlaide.webserver.labels" . | nindent 4 }}
stringData:
  accessKey: {{ .Values.webserver.s3.accessKey }}
  secretKey: {{ .Values.webserver.s3.secretKey }}