apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlaide.fullname" . }}-webserver
  labels:
    {{- include "mlaide.webserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webserver.service.type }}
  ports:
    - port: {{ .Values.webserver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mlaide.webserver.selectorLabels" . | nindent 4 }}
