apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlaide.fullname" . }}-ui
  labels:
    {{- include "mlaide.ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.ui.autoscaling.enabled }}
  replicas: {{ .Values.ui.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mlaide.ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mlaide.ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mlaide.ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      containers:
        - name: ui
          securityContext:
            {{- toYaml .Values.ui.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          env:
            - name: API_URL
              value: "https://{{ .Values.webserver.ingress.domain }}"
            - name: API_VERSION
              value: "v1"
            - name: AUTH_ALLOWED_URLS
              value: "https://{{ .Values.webserver.ingress.domain }}"
            - name: AUTH_AUDIENCE
              value: {{ .Values.oidc.audience }}
            - name: AUTH_CLIEND_ID
              value: {{ .Values.oidc.ui.clientId }}
            - name: AUTH_ISSUER
              value: {{ .Values.oidc.issuer }}
            - name: AUTH_SCOPE
              value: {{ .Values.oidc.scope }}
            - name: AUTH_DISABLE_SECURITY
              value: "false"
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
